name: Deploy WeatherApp In Firebase
on:
  push:
      branches:
        - master
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
    -uses: actions/checkout@master
    -uses: actions/setup-node@master
      with:
        node-version: "16"
    -run: npm install
    -run: npm run build
    -uses: w9jds/firebase-action@master
      with:
        args:deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//0g_C_NAj_QWFYgYIARAAGBASNwF-L9IrKsjm
